# This file was generated by GoReleaser. DO NOT EDIT.
class Sysl < Formula
  desc "Sysl is a tool which generates code and documentation from system specifications"
  homepage "https://sysl.io/"
  version "0.11.0"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/cuminandpaprika/sysl/releases/v0.11.0/sysl_0.11.0_macOS-64bit.tar.gz", :using => CurlDownloadStrategy
    sha256 "786ce676a81ad4c285599a0e62036cf4903f04e9bffdb81f9bb473487aaf6c8f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/cuminandpaprika/sysl/releases/v0.11.0/sysl_0.11.0_Linux-64bit.tar.gz", :using => CurlDownloadStrategy
      sha256 "d9dd02a27d469221c0da100caf7e197d3f2b215cf20cb7d04c1843481a6d55d0"
    end
  end
  
  depends_on "go"
  depends_on "git"

  def install
    bin.install "sysl"
    ...
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/sysl --version"
    ...
  end
end
